### ISSUE TITLE
doesnot works in python 3 or new versions

### ISSUE THREAD

**Issue by optimistab** [DanielPollithy/pypcd#1]
import cStringIO as sio
ModuleNotFoundError: No module named 'cStringIO'

**Comment by DanielPollithy** [comment]
Dear optimistab,
this repo is intended to work with py3 versions.
The line which you are writing `import cStringIO as sio` is not even part of the code. 
Please elaborate on your problem.

The stringIO import works as follows:
```
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
```
